---
title: Trada Tech
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    image: "/assets/img/trada_cover.png"
lang: vi
description: Hiểu đúng làm thực blockchain.
baseurl: "/"
url: https://trada.tech
google_analytics: UA-8597504-5
markdown: kramdown
theme: minima
show_excerpts: true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: blog
      author: Trương Hồng Thi
plugins:
- jekyll-feed
