---
title: Trada Tech
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: "/assets/img/trada_cover.png"
    category: blog
    author: Trương Hồng Thi
lang: vi
description: Hiểu đúng làm thực blockchain.
baseurl: "/"
url: https://trada.tech
google_analytics: UA-8597504-5
markdown: kramdown
theme: minima
show_excerpts: true
plugins:
- jekyll-feed
